import { Cliente } from '@/procesos/pages/GestionarProyectos/Types';

export const clientesDummyData: Cliente[] = [
  {
    ruc: "20123456789",
    razonSocial: "Tech Solutions S.A.C.",
    ubicacion: "Av. Javier Prado 2500, San Isidro, Lima",
    contacto: "+51 987 654 321",
    nombreContacto: "Carlos Mendoza Rivera",
    plataformaFacturacion: "https://e-factura.sunat.gob.pe",
    usuarioPlataforma: "techsolutions2023",
    contrasenaPlataforma: "TechS0l2023!",
    comentarios: "Cliente corporativo de alto valor. Preferencia por proyectos de gran escala.",
    fechaRegistro: "2023-03-15",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 150000,
    proyectosAsociados: ["PROJ-001", "PROJ-015"]
  },
  {
    ruc: "20456789012",
    razonSocial: "Municipalidad Distrital de Lima",
    ubicacion: "Jr. de la Unión 300, Cercado de Lima",
    contacto: "contacto@munilima.gob.pe",
    nombreContacto: "Ana Patricia Quispe Flores",
    plataformaFacturacion: "https://portal.osce.gob.pe",
    usuarioPlataforma: "munilima_compras",
    contrasenaPlataforma: "MuniL1m@2024",
    comentarios: "Entidad gubernamental. Requiere proceso de licitación para compras mayores a S/. 40,000. Contactar con 45 días de anticipación.",
    fechaRegistro: "2022-08-10",
    estado: "activo",
    tipoCliente: "gobierno",
    limiteCredito: 500000,
    proyectosAsociados: ["PROJ-022", "PROJ-025"]
  },
  {
    ruc: "20789012345",
    razonSocial: "Complejo Industrial Norte S.A.",
    ubicacion: "Km 35 Panamericana Norte, Puente Piedra, Lima",
    contacto: "+51 998 765 432",
    nombreContacto: "Roberto Díaz Salazar",
    plataformaFacturacion: "https://www.nubefact.com",
    usuarioPlataforma: "cin_facturacion",
    contrasenaPlataforma: "CIN#Ind2023",
    comentarios: "Planta industrial con requerimientos específicos de seguridad. Facturación cada 15 días.",
    fechaRegistro: "2023-06-22",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 200000,
    proyectosAsociados: ["PROJ-030"]
  },
  {
    ruc: "20345678901",
    razonSocial: "Corporación Minera del Sur E.I.R.L.",
    ubicacion: "Av. Los Incas 890, Arequipa",
    contacto: "compras@minerasur.com.pe",
    nombreContacto: "Miguel Ángel Torres Campos",
    plataformaFacturacion: "https://www.facturaperu.com",
    usuarioPlataforma: "minerasur_admin",
    contrasenaPlataforma: "M1n3r@Sur24",
    comentarios: "Cliente con operaciones en zona sur del país. Requiere certificaciones ISO para productos de seguridad.",
    fechaRegistro: "2022-11-05",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 300000,
    proyectosAsociados: []
  },
  {
    ruc: "20567890123",
    razonSocial: "Hospital Regional de Salud",
    ubicacion: "Av. Grau 1350, Lima",
    contacto: "+51 912 345 678",
    nombreContacto: "Dra. Patricia Romero Vega",
    plataformaFacturacion: "https://e-factura.sunat.gob.pe",
    usuarioPlataforma: "hospitalregional2024",
    contrasenaPlataforma: "H0sp1t@lR24",
    comentarios: "Institución de salud pública. Prioridad en equipos médicos de emergencia. Proceso de compra lento pero seguro.",
    fechaRegistro: "2024-01-20",
    estado: "activo",
    tipoCliente: "gobierno",
    limiteCredito: 180000,
    proyectosAsociados: ["PROJ-012"]
  },
  {
    ruc: "20890123456",
    razonSocial: "Universidad Nacional del Centro",
    ubicacion: "Av. Universitaria 456, Huancayo",
    contacto: "logistica@uncentro.edu.pe",
    nombreContacto: "Ing. Jorge Luis Paredes Luna",
    plataformaFacturacion: "https://portal.sunat.gob.pe",
    usuarioPlataforma: "uncentro_compras",
    contrasenaPlataforma: "UnC3ntr0#24",
    comentarios: "Universidad pública con presupuesto limitado. Requieren cotizaciones detalladas y comparativas.",
    fechaRegistro: "2023-09-12",
    estado: "activo",
    tipoCliente: "gobierno",
    limiteCredito: 100000,
    proyectosAsociados: []
  },
  {
    ruc: "20234567890",
    razonSocial: "Centro Comercial Plaza del Sol S.A.C.",
    ubicacion: "Av. Larco 1234, Miraflores, Lima",
    contacto: "+51 923 456 789",
    nombreContacto: "Carla Sofía Mendez Ruiz",
    plataformaFacturacion: "https://www.mifactura.pe",
    usuarioPlataforma: "plazasol_admin",
    contrasenaPlataforma: "Pl@z@S0l24!",
    comentarios: "Centro comercial con alto tráfico. Requieren sistemas de seguridad y equipos de emergencia certificados.",
    fechaRegistro: "2024-02-08",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 120000,
    proyectosAsociados: []
  },
  {
    ruc: "20678901234",
    razonSocial: "Constructora Horizonte Perú S.A.",
    ubicacion: "Jr. Las Camelias 678, San Isidro, Lima",
    contacto: "proyectos@horizonteperu.com",
    nombreContacto: "Arq. Fernando Castillo Ramos",
    plataformaFacturacion: "https://www.sunat.gob.pe",
    usuarioPlataforma: "horizonte_factura",
    contrasenaPlataforma: "H0r1z0nt3!24",
    comentarios: "Constructora con múltiples proyectos simultáneos. Pagos puntuales a 30 días.",
    fechaRegistro: "2023-04-18",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 250000,
    proyectosAsociados: ["PROJ-008"]
  },
  {
    ruc: "20456123789",
    razonSocial: "Distribuidora Nacional E.I.R.L.",
    ubicacion: "Av. Industrial 2345, Ate, Lima",
    contacto: "+51 934 567 890",
    nombreContacto: "Luis Alberto Sánchez Pérez",
    plataformaFacturacion: "https://facturador.pe",
    usuarioPlataforma: "disnacional2024",
    contrasenaPlataforma: "D1sN@c24!",
    comentarios: "Distribuidor mayorista. Interesado en compras al por mayor con descuentos.",
    fechaRegistro: "2023-12-01",
    estado: "activo",
    tipoCliente: "pyme",
    limiteCredito: 80000,
    proyectosAsociados: []
  },
  {
    ruc: "20789456123",
    razonSocial: "Agroindustrias del Valle S.A.C.",
    ubicacion: "Km 12 Carretera Ica, Ica",
    contacto: "administracion@agrovalles.com.pe",
    nombreContacto: "Ing. María Elena Vargas Díaz",
    plataformaFacturacion: "https://www.nubefact.com",
    usuarioPlataforma: "agrovalles_admin",
    contrasenaPlataforma: "Agr0V@ll3s24",
    comentarios: "Empresa agroindustrial en expansión. Requieren equipos de seguridad para planta procesadora.",
    fechaRegistro: "2024-03-05",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 150000,
    proyectosAsociados: []
  },
  {
    ruc: "20123789456",
    razonSocial: "Inversiones Comerciales del Norte S.R.L.",
    ubicacion: "Av. América 567, Trujillo",
    contacto: "+51 945 678 901",
    nombreContacto: "César Augusto Flores Rojas",
    plataformaFacturacion: "https://e-factura.sunat.gob.pe",
    usuarioPlataforma: "invnorte2024",
    contrasenaPlataforma: "InvN0rt3!24",
    comentarios: "Grupo empresarial con presencia en norte del país. Clientes recurrentes.",
    fechaRegistro: "2022-07-15",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 200000,
    proyectosAsociados: []
  },
  {
    ruc: "20345123678",
    razonSocial: "Servicios Logísticos Express S.A.",
    ubicacion: "Av. Venezuela 1890, Callao",
    contacto: "operaciones@logexpress.pe",
    nombreContacto: "Javier Antonio Guzmán Silva",
    plataformaFacturacion: "https://www.facturaperu.com",
    usuarioPlataforma: "logexpress_fact",
    contrasenaPlataforma: "L0gExpr3ss24!",
    comentarios: "Empresa de logística y transporte. Requieren equipos de seguridad para flota vehicular.",
    fechaRegistro: "2023-11-20",
    estado: "activo",
    tipoCliente: "pyme",
    limiteCredito: 90000,
    proyectosAsociados: []
  },
  {
    ruc: "20567234901",
    razonSocial: "Grupo Hotelero Costa Verde S.A.C.",
    ubicacion: "Malecón Cisneros 1456, Miraflores, Lima",
    contacto: "+51 956 789 012",
    nombreContacto: "Lic. Andrea Valeria Campos Núñez",
    plataformaFacturacion: "https://www.mifactura.pe",
    usuarioPlataforma: "costaverde_hotel",
    contrasenaPlataforma: "C0st@V3rd3!24",
    comentarios: "Cadena hotelera con múltiples sedes. Requieren certificaciones de seguridad contra incendios.",
    fechaRegistro: "2024-01-10",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 160000,
    proyectosAsociados: []
  },
  {
    ruc: "20890567234",
    razonSocial: "Textiles Andinos del Sur E.I.R.L.",
    ubicacion: "Jr. Gamarra 890, La Victoria, Lima",
    contacto: "ventas@textilesandinos.pe",
    nombreContacto: "Rosa María Huamán Quispe",
    plataformaFacturacion: "https://facturador.pe",
    usuarioPlataforma: "textandinos24",
    contrasenaPlataforma: "T3xt1l3s@24",
    comentarios: "Empresa textil familiar en crecimiento. Pagos en efectivo o transferencia inmediata.",
    fechaRegistro: "2023-05-08",
    estado: "suspendido",
    tipoCliente: "pyme",
    limiteCredito: 50000,
    proyectosAsociados: []
  },
  {
    ruc: "20234890567",
    razonSocial: "Telecomunicaciones Digital S.A.",
    ubicacion: "Av. Arequipa 3456, Lince, Lima",
    contacto: "+51 967 890 123",
    nombreContacto: "Ing. Diego Martín Espinoza Paredes",
    plataformaFacturacion: "https://www.sunat.gob.pe",
    usuarioPlataforma: "teledigital_admin",
    contrasenaPlataforma: "T3l3D1g!24",
    comentarios: "Empresa de telecomunicaciones en expansión. Cliente nuevo con buen potencial.",
    fechaRegistro: "2024-04-15",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 180000,
    proyectosAsociados: []
  },
  {
    ruc: "20678345012",
    razonSocial: "Farmacéutica MediPlus S.A.C.",
    ubicacion: "Av. Brasil 2345, Breña, Lima",
    contacto: "compras@mediplus.com.pe",
    nombreContacto: "Q.F. Carmen Lucía Herrera Robles",
    plataformaFacturacion: "https://e-factura.sunat.gob.pe",
    usuarioPlataforma: "mediplus2024",
    contrasenaPlataforma: "M3d1Plu$24!",
    comentarios: "Cadena de farmacias. Requieren kits de emergencia y primeros auxilios certificados.",
    fechaRegistro: "2023-08-25",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 140000,
    proyectosAsociados: []
  },
  {
    ruc: "20456890234",
    razonSocial: "Servicios Financieros BancoSur S.A.",
    ubicacion: "Av. Primavera 1234, Surco, Lima",
    contacto: "+51 978 901 234",
    nombreContacto: "Lic. Ricardo Alonso Morales Vega",
    plataformaFacturacion: "https://portal.sunat.gob.pe",
    usuarioPlataforma: "bancosur_fact",
    contrasenaPlataforma: "B@nc0Sur24!",
    comentarios: "Institución financiera. Requieren sistemas de seguridad de alta tecnología. Proceso de aprobación lento.",
    fechaRegistro: "2023-02-28",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 400000,
    proyectosAsociados: []
  },
  {
    ruc: "20789678345",
    razonSocial: "Alimentos Nutritivos del Perú S.A.C.",
    ubicacion: "Av. Argentina 4567, Callao",
    contacto: "logistica@alimentosnutri.pe",
    nombreContacto: "Ing. Sandra Beatriz Córdova Villanueva",
    plataformaFacturacion: "https://www.nubefact.com",
    usuarioPlataforma: "alinutri_admin",
    contrasenaPlataforma: "Al1Nutr1!24",
    comentarios: "Planta procesadora de alimentos. Cumplimiento estricto de normas de seguridad alimentaria.",
    fechaRegistro: "2024-02-20",
    estado: "activo",
    tipoCliente: "corporativo",
    limiteCredito: 170000,
    proyectosAsociados: []
  },
  {
    ruc: "20123678234",
    razonSocial: "Transporte Rápido Nacional S.R.L.",
    ubicacion: "Av. Colonial 789, Lima",
    contacto: "+51 989 012 345",
    nombreContacto: "Sr. Héctor Raúl Domínguez Castro",
    plataformaFacturacion: "https://facturador.pe",
    usuarioPlataforma: "transrapido24",
    contrasenaPlataforma: "Tr@nsR@p!24",
    comentarios: "Empresa de transporte interprovincial. Requieren equipos de seguridad vehicular.",
    fechaRegistro: "2023-10-12",
    estado: "inactivo",
    tipoCliente: "pyme",
    limiteCredito: 60000,
    proyectosAsociados: []
  },
  {
    ruc: "20345901678",
    razonSocial: "Educación Superior TechAcademy S.A.C.",
    ubicacion: "Av. Universitaria 2890, Los Olivos, Lima",
    contacto: "administracion@techacademy.edu.pe",
    nombreContacto: "Mg. Laura Isabel Fernández Gutiérrez",
    plataformaFacturacion: "https://www.mifactura.pe",
    usuarioPlataforma: "techacademy2024",
    contrasenaPlataforma: "T3chAc@d!24",
    comentarios: "Instituto de educación superior. Requieren equipos de laboratorio y seguridad para instalaciones.",
    fechaRegistro: "2024-03-18",
    estado: "activo",
    tipoCliente: "pyme",
    limiteCredito: 95000,
    proyectosAsociados: []
  }
];

// Funciones auxiliares
export const getClientesActivos = () => clientesDummyData.filter(c => c.estado === "activo");
export const getClientesInactivos = () => clientesDummyData.filter(c => c.estado !== "activo");
export const getClienteByRuc = (ruc: string) => clientesDummyData.find(c => c.ruc === ruc);
export const getClientesByTipo = (tipo: string) => clientesDummyData.filter(c => c.tipoCliente === tipo);
export const getClientesConProyectos = () => clientesDummyData.filter(c => c.proyectosAsociados && c.proyectosAsociados.length > 0);

// Estadísticas de clientes
export const getClientesStats = () => {
  const total = clientesDummyData.length;
  const activos = getClientesActivos().length;
  const inactivos = clientesDummyData.filter(c => c.estado === "inactivo").length;
  const suspendidos = clientesDummyData.filter(c => c.estado === "suspendido").length;
  const corporativos = clientesDummyData.filter(c => c.tipoCliente === "corporativo").length;
  const gobierno = clientesDummyData.filter(c => c.tipoCliente === "gobierno").length;
  const pymes = clientesDummyData.filter(c => c.tipoCliente === "pyme").length;
  const totalLimiteCredito = clientesDummyData.reduce((sum, c) => sum + (c.limiteCredito || 0), 0);
  
  return {
    total,
    activos,
    inactivos,
    suspendidos,
    corporativos,
    gobierno,
    pymes,
    totalLimiteCredito,
    porcentajeActivos: ((activos / total) * 100).toFixed(1)
  };
};