import { Item } from '@/Inventario/pages/types';

export const inventarioDummyData: Item[] = [
  {
    id: "I001",
    nombre: "Extintor CO2 10lb",
    fabricante: "Kidde",
    numero_serial: "EX12345",
    lugar_almacenaje: "Camión 03",
    cantidad: 5,
    estado: "disponible",
    categoria: "Equipos de Extinción",
    descripcion: "Extintor de dióxido de carbono de 10 libras para fuegos tipo B y C",
    fecha_adquisicion: "2023-03-15",
    fecha_ultima_revision: "2024-11-10",
    costo_unitario: 350.00,
    proveedor: "Fire Safety Systems SAC",
    observaciones: "Revisión anual pendiente para febrero 2025"
  },
  {
    id: "I002",
    nombre: "Manguera 1.5'' 30m",
    fabricante: "Angus Fire",
    numero_serial: "MGH7890",
    lugar_almacenaje: "Depósito Central",
    cantidad: 10,
    estado: "en_reparacion",
    categoria: "Equipos de Supresión",
    descripcion: "Manguera contra incendios de 1.5 pulgadas y 30 metros de longitud",
    fecha_adquisicion: "2022-08-20",
    fecha_ultima_revision: "2024-10-05",
    costo_unitario: 280.00,
    proveedor: "Hydro Equipment Perú",
    observaciones: "3 unidades con fugas menores en reparación"
  },
  {
    id: "I003",
    nombre: "Casco de Bombero F1",
    fabricante: "MSA Safety",
    numero_serial: "CSC4567",
    lugar_almacenaje: "Almacén de EPP - Estante A3",
    cantidad: 25,
    estado: "disponible",
    categoria: "Equipos de Protección Personal",
    descripcion: "Casco estructural para bomberos con visor y protección cervical",
    fecha_adquisicion: "2024-01-10",
    fecha_ultima_revision: "2024-09-15",
    costo_unitario: 450.00,
    proveedor: "Safety Gear International",
    observaciones: "Stock completo, buenas condiciones"
  },
  {
    id: "I004",
    nombre: "Traje Bunker Completo",
    fabricante: "Globe",
    numero_serial: "TB9012",
    lugar_almacenaje: "Vestidor Principal",
    cantidad: 18,
    estado: "disponible",
    categoria: "Equipos de Protección Personal",
    descripcion: "Traje estructural completo resistente al fuego con certificación NFPA",
    fecha_adquisicion: "2023-11-25",
    fecha_ultima_revision: "2024-10-20",
    costo_unitario: 1850.00,
    proveedor: "Fire Safety Systems SAC",
    observaciones: "2 trajes requieren reemplazo de cierres en próximo mantenimiento"
  },
  {
    id: "I005",
    nombre: "Equipo de Respiración Autónoma SCBA",
    fabricante: "Dräger",
    numero_serial: "SCBA2234",
    lugar_almacenaje: "Camión 01 - Compartimento 2",
    cantidad: 8,
    estado: "disponible",
    categoria: "Equipos Respiratorios",
    descripcion: "Sistema de respiración autónoma con cilindro de 45 minutos",
    fecha_adquisicion: "2023-06-12",
    fecha_ultima_revision: "2024-11-05",
    costo_unitario: 3200.00,
    proveedor: "Respir-Tech Solutions",
    observaciones: "Cilindros con prueba hidrostática vigente hasta 2026"
  },
  {
    id: "I006",
    nombre: "Botas de Bombero Estructurales",
    fabricante: "Haix",
    numero_serial: "BT5678",
    lugar_almacenaje: "Almacén de EPP - Estante B1",
    cantidad: 30,
    estado: "disponible",
    categoria: "Equipos de Protección Personal",
    descripcion: "Botas estructurales impermeables con punta de acero",
    fecha_adquisicion: "2024-02-18",
    fecha_ultima_revision: "2024-08-30",
    costo_unitario: 320.00,
    proveedor: "Safety Gear International",
    observaciones: "Incluye tallas desde 38 hasta 45"
  },
  {
    id: "I007",
    nombre: "Hacha de Bombero Plana",
    fabricante: "Council Tool",
    numero_serial: "AX3456",
    lugar_almacenaje: "Camión 02 - Rack de Herramientas",
    cantidad: 12,
    estado: "disponible",
    categoria: "Herramientas de Forcejeo",
    descripcion: "Hacha plana de 36 pulgadas con mango de fibra de vidrio",
    fecha_adquisicion: "2023-04-08",
    fecha_ultima_revision: "2024-07-22",
    costo_unitario: 180.00,
    proveedor: "Fire Tools Depot",
    observaciones: "Requieren afilado periódico"
  },
  {
    id: "I008",
    nombre: "Cámara Térmica TIC",
    fabricante: "FLIR",
    numero_serial: "TIC7890",
    lugar_almacenaje: "Camión 01 - Cabina de Mando",
    cantidad: 3,
    estado: "disponible",
    categoria: "Equipos de Detección",
    descripcion: "Cámara térmica de imagen para búsqueda y rescate",
    fecha_adquisicion: "2024-05-20",
    fecha_ultima_revision: "2024-11-12",
    costo_unitario: 8500.00,
    proveedor: "Tech Fire Solutions",
    observaciones: "Última calibración: noviembre 2024, próxima en mayo 2025"
  },
  {
    id: "I009",
    nombre: "Linterna LED Alta Potencia",
    fabricante: "Streamlight",
    numero_serial: "LT4567",
    lugar_almacenaje: "Depósito Central - Caja 12",
    cantidad: 40,
    estado: "disponible",
    categoria: "Equipos de Iluminación",
    descripcion: "Linterna LED recargable de 1000 lúmenes resistente al agua",
    fecha_adquisicion: "2023-09-14",
    fecha_ultima_revision: "2024-10-08",
    costo_unitario: 120.00,
    proveedor: "Lighting Pro",
    observaciones: "Baterías con vida útil promedio de 3 años"
  },
  {
    id: "I010",
    nombre: "Radio Portátil VHF",
    fabricante: "Motorola",
    numero_serial: "RD8901",
    lugar_almacenaje: "Estación Central - Oficina Comunicaciones",
    cantidad: 15,
    estado: "disponible",
    categoria: "Equipos de Comunicación",
    descripcion: "Radio portátil de dos vías con alcance de 5km",
    fecha_adquisicion: "2023-07-30",
    fecha_ultima_revision: "2024-09-25",
    costo_unitario: 450.00,
    proveedor: "Communications Tech",
    observaciones: "Programados en canal de emergencia 155.340 MHz"
  },
  {
    id: "I011",
    nombre: "Escalera Extensible 7.5m",
    fabricante: "Little Giant",
    numero_serial: "ESC2345",
    lugar_almacenaje: "Camión 03 - Exterior",
    cantidad: 4,
    estado: "disponible",
    categoria: "Equipos de Acceso",
    descripcion: "Escalera de aluminio extensible de 3 secciones",
    fecha_adquisicion: "2022-12-10",
    fecha_ultima_revision: "2024-08-15",
    costo_unitario: 980.00,
    proveedor: "Ladder Systems Inc",
    observaciones: "Inspección trimestral obligatoria"
  },
  {
    id: "I012",
    nombre: "Bomba Portátil de Agua",
    fabricante: "Honda",
    numero_serial: "BP6789",
    lugar_almacenaje: "Garage de Mantenimiento",
    cantidad: 2,
    estado: "en_reparacion",
    categoria: "Equipos de Bombeo",
    descripcion: "Motobomba portátil 1000 GPM para operaciones de achique",
    fecha_adquisicion: "2021-05-18",
    fecha_ultima_revision: "2024-10-30",
    costo_unitario: 2200.00,
    proveedor: "Pump Equipment SAC",
    observaciones: "Una unidad en mantenimiento por cambio de motor"
  },
  {
    id: "I013",
    nombre: "Cuerdas de Rescate 50m",
    fabricante: "Sterling Rope",
    numero_serial: "CR4567",
    lugar_almacenaje: "Camión 02 - Compartimento 4",
    cantidad: 8,
    estado: "disponible",
    categoria: "Equipos de Rescate",
    descripcion: "Cuerda estática de rescate de 11mm x 50m certificada NFPA",
    fecha_adquisicion: "2023-08-22",
    fecha_ultima_revision: "2024-11-01",
    costo_unitario: 420.00,
    proveedor: "Rescue Gear Pro",
    observaciones: "Fecha de retiro programada: agosto 2028"
  },
  {
    id: "I014",
    nombre: "Kit de Primeros Auxilios Avanzado",
    fabricante: "Medline",
    numero_serial: "KPA8901",
    lugar_almacenaje: "Camión 01 - Compartimento Médico",
    cantidad: 6,
    estado: "disponible",
    categoria: "Equipos Médicos",
    descripcion: "Kit completo con suministros para trauma y emergencias",
    fecha_adquisicion: "2024-03-05",
    fecha_ultima_revision: "2024-11-18",
    costo_unitario: 380.00,
    proveedor: "Medical Supplies Peru",
    observaciones: "Revisar fechas de vencimiento mensualmente"
  },
  {
    id: "I015",
    nombre: "Guantes de Bombero Estructurales",
    fabricante: "Dragon Fire",
    numero_serial: "GU3456",
    lugar_almacenaje: "Almacén de EPP - Estante C2",
    cantidad: 50,
    estado: "disponible",
    categoria: "Equipos de Protección Personal",
    descripcion: "Guantes resistentes al calor con refuerzo en palma",
    fecha_adquisicion: "2024-01-28",
    fecha_ultima_revision: "2024-10-12",
    costo_unitario: 95.00,
    proveedor: "Safety Gear International",
    observaciones: "Disponibles en tallas M, L, XL"
  },
  {
    id: "I016",
    nombre: "Detector de Gas Multigas",
    fabricante: "BW Technologies",
    numero_serial: "DG7890",
    lugar_almacenaje: "Estación Central - Armario de Equipos",
    cantidad: 5,
    estado: "disponible",
    categoria: "Equipos de Detección",
    descripcion: "Detector portátil de 4 gases (O2, LEL, CO, H2S)",
    fecha_adquisicion: "2023-10-15",
    fecha_ultima_revision: "2024-11-20",
    costo_unitario: 1250.00,
    proveedor: "Gas Detection Systems",
    observaciones: "Calibración semestral obligatoria, última: nov 2024"
  },
  {
    id: "I017",
    nombre: "Cortador Hidráulico de Rescate",
    fabricante: "Holmatro",
    numero_serial: "CH1234",
    lugar_almacenaje: "Camión 01 - Compartimento de Rescate",
    cantidad: 2,
    estado: "disponible",
    categoria: "Herramientas de Rescate",
    descripcion: "Cortador hidráulico para extracción vehicular",
    fecha_adquisicion: "2022-11-08",
    fecha_ultima_revision: "2024-09-18",
    costo_unitario: 12500.00,
    proveedor: "Rescue Equipment International",
    observaciones: "Mantenimiento hidráulico cada 6 meses"
  },
  {
    id: "I018",
    nombre: "Monitor de Ventilación PPV",
    fabricante: "Super Vac",
    numero_serial: "MV5678",
    lugar_almacenaje: "Camión 02 - Compartimento 3",
    cantidad: 3,
    estado: "daniado",
    categoria: "Equipos de Ventilación",
    descripcion: "Ventilador de presión positiva para extracción de humo",
    fecha_adquisicion: "2021-06-22",
    fecha_ultima_revision: "2024-08-10",
    costo_unitario: 2800.00,
    proveedor: "Fire Ventilation Systems",
    observaciones: "1 unidad dañada por caída, requiere reemplazo de motor"
  },
  {
    id: "I019",
    nombre: "Camilla Rígida de Rescate",
    fabricante: "Ferno",
    numero_serial: "CM9012",
    lugar_almacenaje: "Camión 03 - Compartimento Médico",
    cantidad: 4,
    estado: "disponible",
    categoria: "Equipos Médicos",
    descripcion: "Camilla espinal rígida con inmovilizadores",
    fecha_adquisicion: "2023-02-14",
    fecha_ultima_revision: "2024-10-28",
    costo_unitario: 680.00,
    proveedor: "Medical Rescue Equipment",
    observaciones: "Incluye correas y bloques de cabeza"
  },
  {
    id: "I020",
    nombre: "Generador Portátil 5kW",
    fabricante: "Yamaha",
    numero_serial: "GN3456",
    lugar_almacenaje: "Garage de Mantenimiento",
    cantidad: 3,
    estado: "disponible",
    categoria: "Equipos de Energía",
    descripcion: "Generador eléctrico portátil de 5000W para emergencias",
    fecha_adquisicion: "2023-05-30",
    fecha_ultima_revision: "2024-11-15",
    costo_unitario: 3500.00,
    proveedor: "Power Solutions Peru",
    observaciones: "Mantenimiento preventivo trimestral, combustible renovado mensualmente"
  },
  {
    id: "I021",
    nombre: "Chaqueta de Bombero Wildland",
    fabricante: "Tecasafe Plus",
    numero_serial: "CW7890",
    lugar_almacenaje: "Almacén de EPP - Perchero D",
    cantidad: 20,
    estado: "disponible",
    categoria: "Equipos de Protección Personal",
    descripcion: "Chaqueta ligera para combate de incendios forestales",
    fecha_adquisicion: "2024-04-12",
    fecha_ultima_revision: "2024-10-05",
    costo_unitario: 280.00,
    proveedor: "Wildland Fire Gear",
    observaciones: "Material ignífugo con reflejos amarillos"
  },
  {
    id: "I022",
    nombre: "Barra Halligan 30''",
    fabricante: "Council Tool",
    numero_serial: "BH4567",
    lugar_almacenaje: "Camión 01 - Rack de Herramientas",
    cantidad: 10,
    estado: "disponible",
    categoria: "Herramientas de Forcejeo",
    descripcion: "Barra de forcejeo multifuncional de 30 pulgadas",
    fecha_adquisicion: "2023-07-18",
    fecha_ultima_revision: "2024-09-08",
    costo_unitario: 220.00,
    proveedor: "Fire Tools Depot",
    observaciones: "Herramienta esencial para entrada forzada"
  },
  {
    id: "I023",
    nombre: "Cono de Tráfico Reflectivo",
    fabricante: "Traffic Safety Corp",
    numero_serial: "CT8901",
    lugar_almacenaje: "Depósito Central - Área Externa",
    cantidad: 100,
    estado: "disponible",
    categoria: "Equipos de Señalización",
    descripcion: "Conos de 75cm con bandas reflectivas",
    fecha_adquisicion: "2023-01-20",
    fecha_ultima_revision: "2024-06-15",
    costo_unitario: 15.00,
    proveedor: "Traffic Equipment SAC",
    observaciones: "Algunos conos con decoloración por exposición solar"
  },
  {
    id: "I024",
    nombre: "Oxímetro de Pulso Portátil",
    fabricante: "Masimo",
    numero_serial: "OX2345",
    lugar_almacenaje: "Camión 02 - Kit Médico",
    cantidad: 8,
    estado: "disponible",
    categoria: "Equipos Médicos",
    descripcion: "Oxímetro digital para medir saturación de oxígeno",
    fecha_adquisicion: "2024-06-08",
    fecha_ultima_revision: "2024-11-10",
    costo_unitario: 180.00,
    proveedor: "Medical Tech Solutions",
    observaciones: "Baterías AAA incluidas, reemplazar cada 6 meses"
  },
  {
    id: "I025",
    nombre: "Equipo SCBA de Repuesto (Cilindro)",
    fabricante: "Dräger",
    numero_serial: "CIL6789",
    lugar_almacenaje: "Estación Central - Rack de Cilindros",
    cantidad: 12,
    estado: "retirado",
    categoria: "Equipos Respiratorios",
    descripcion: "Cilindro de aire comprimido 4500 PSI vencido",
    fecha_adquisicion: "2018-03-22",
    fecha_ultima_revision: "2023-03-22",
    costo_unitario: 850.00,
    proveedor: "Respir-Tech Solutions",
    observaciones: "Retirados de servicio por vencimiento de prueba hidrostática, pendiente de disposición"
  }
];

// Funciones auxiliares
export const getAvailableItems = () => inventarioDummyData.filter(i => i.estado === "disponible");
export const getUnavailableItems = () => inventarioDummyData.filter(i => i.estado !== "disponible");
export const getItemsByCategoria = (categoria: string) => inventarioDummyData.filter(i => i.categoria === categoria);
export const getItemById = (id: string) => inventarioDummyData.find(i => i.id === id);
export const getItemsByEstado = (estado: string) => inventarioDummyData.filter(i => i.estado === estado);
export const getLowStockItems = (threshold: number = 5) => inventarioDummyData.filter(i => i.cantidad <= threshold);

// Estadísticas útiles
export const getInventarioStats = () => {
  const total = inventarioDummyData.length;
  const disponibles = getAvailableItems().length;
  const enReparacion = inventarioDummyData.filter(i => i.estado === "en_reparacion").length;
  const daniados = inventarioDummyData.filter(i => i.estado === "daniado").length;
  const retirados = inventarioDummyData.filter(i => i.estado === "retirado").length;
  const totalValor = inventarioDummyData.reduce((sum, item) => sum + (item.costo_unitario || 0) * item.cantidad, 0);
  
  return {
    total,
    disponibles,
    enReparacion,
    daniados,
    retirados,
    totalValor,
    porcentajeDisponible: ((disponibles / total) * 100).toFixed(1)
  };
};

// Categorías únicas
export const getCategorias = () => {
  const categorias = new Set(inventarioDummyData.map(i => i.categoria).filter(Boolean));
  return Array.from(categorias).sort();
};